import { KEYS, storage } from "../storage";
import { findModel } from "../catalog";
import { shortId } from "../utils";
import type { Generation, ImageParams, VideoParams } from "../types";
import { LumenApiError } from "./index";
import { setTitleIfDefaultSync, touchSync } from "./sessions";
import { getAdapter } from "../providers/registry";
import {
  AdapterError,
  modelToProviderConfig,
  type AdapterEvent,
  type GenerateRequest,
} from "../providers/base";
import { registerJob, publishProgress, publishFinal } from "../live-jobs";

export interface ImageRequest {
  userId: string;
  /** Required when starting a new turn within a session; omit for one-offs. */
  sessionId?: string;
  modelId: string;
  prompt: string;
  params: ImageParams;
}

export interface VideoRequest {
  userId: string;
  sessionId?: string;
  modelId: string;
  prompt: string;
  params: VideoParams;
}

interface PendingJob {
  id: string;
  cancel: () => void;
}

const activeJobs = new Map<string, PendingJob>();

/**
 * Strip large reference image base64s before writing to localStorage.
 * Each upload can be several MB; even a handful of generations would exceed
 * the ~5MB quota. We keep the count so the UI can still indicate that
 * references were used, but drop the actual bytes — they're regenerated by
 * re-uploading on rerun and replaced by OSS URLs once a real backend is
 * connected.
 */
function leanForStorage(g: Generation): Generation {
  const lean: Generation = { ...g };
  if (g.imageParams?.references && g.imageParams.references.length > 0) {
    lean.imageParams = {
      ...g.imageParams,
      references: g.imageParams.references.map(() => "ref:omitted"),
    };
  }
  if (g.videoParams?.referenceImageUrl && g.videoParams.referenceImageUrl.startsWith("data:")) {
    lean.videoParams = {
      ...g.videoParams,
      referenceImageUrl: "ref:omitted",
    };
  }
  return lean;
}

function persistGeneration(g: Generation) {
  const list = storage.get<Generation[]>(KEYS.generations, []);
  const lean = leanForStorage(g);
  const idx = list.findIndex((x) => x.id === g.id);
  if (idx >= 0) list[idx] = lean;
  else list.unshift(lean);
  storage.set(KEYS.generations, list);
}

/**
 * Common runner for both image and video. Resolves the adapter from the
 * registry, drives the async generator, and maps progress / final / error
 * back into the Generation record + onProgress callback shape that the UI
 * has used since stage 1.
 */
function runAdapter(
  initial: Generation,
  request: GenerateRequest,
  modelId: string,
  onProgress?: (pct: number, gen: Generation) => void,
): { id: string; promise: Promise<Generation>; cancel: () => void } {
  const id = initial.id;
  const model = findModel(modelId);
  if (!model) {
    throw new LumenApiError("NOT_FOUND", "选择的模型不可用");
  }
  const adapter = getAdapter(model.providerType, model.kind);
  const cfg = modelToProviderConfig(model);
  const controller = new AbortController();
  request.signal = controller.signal;

  const startedAt = Date.now();

  const cancel = () => controller.abort();
  // 模块级注册：跨组件挂载/路由切换保持 in-flight 进度
  registerJob(id, { ...initial, status: "running" }, cancel);

  const promise = (async (): Promise<Generation> => {
    try {
      const stream = adapter.generate(cfg, request);
      let final: Generation | null = null;
      for await (const ev of stream as AsyncIterable<AdapterEvent>) {
        if (ev.type === "progress") {
          const updated: Generation = { ...initial, status: "running" };
          onProgress?.(ev.pct, updated);
          publishProgress(id, ev.pct, updated);
          continue;
        }
        // FinalResult
        const completedAt = new Date().toISOString();
        const durationMs = Date.now() - startedAt;
        final = {
          ...initial,
          status: "succeeded",
          completedAt,
          durationMs,
          cost: ev.cost,
          ...(ev.kind === "image"
            ? { imageUrls: ev.imageUrls }
            : { videoUrl: ev.videoUrl, videoPosterUrl: ev.videoPosterUrl }),
        };
      }
      if (!final) {
        throw new AdapterError("upstream_5xx", "上游未返回结果");
      }
      persistGeneration(final);
      activeJobs.delete(id);
      publishFinal(id, final);
      return final;
    } catch (err) {
      const ae = err instanceof AdapterError ? err : new AdapterError("network", String((err as Error)?.message ?? err));
      const failed: Generation = {
        ...initial,
        status: "failed",
        completedAt: new Date().toISOString(),
        durationMs: Date.now() - startedAt,
        errorMessage: ae.message,
      };
      persistGeneration(failed);
      activeJobs.delete(id);
      publishFinal(id, failed);
      return failed;
    }
  })();

  activeJobs.set(id, { id, cancel });
  return { id, promise, cancel };
}

/**
 * Start an image generation. Returns a job handle that emits progress
 * events; the resolved promise produces the final Generation.
 */
export function generateImage(
  req: ImageRequest,
  onProgress?: (pct: number, gen: Generation) => void,
): { id: string; promise: Promise<Generation>; cancel: () => void } {
  const model = findModel(req.modelId);
  if (!model || model.kind !== "image") {
    throw new LumenApiError("NOT_FOUND", "选择的模型不可用");
  }
  const id = shortId("g_");
  const createdAt = new Date().toISOString();
  const initial: Generation = {
    id,
    userId: req.userId,
    sessionId: req.sessionId,
    kind: "image",
    modelId: req.modelId,
    prompt: req.prompt,
    status: "running",
    createdAt,
    imageParams: req.params,
  };
  persistGeneration(initial);
  if (req.sessionId) {
    setTitleIfDefaultSync(req.sessionId, req.prompt);
    touchSync(req.sessionId);
  }
  return runAdapter(initial, { kind: "image", prompt: req.prompt, params: req.params }, req.modelId, onProgress);
}

export function generateVideo(
  req: VideoRequest,
  onProgress?: (pct: number, gen: Generation) => void,
): { id: string; promise: Promise<Generation>; cancel: () => void } {
  const model = findModel(req.modelId);
  if (!model || model.kind !== "video") {
    throw new LumenApiError("NOT_FOUND", "选择的模型不可用");
  }
  const id = shortId("g_");
  const createdAt = new Date().toISOString();
  const initial: Generation = {
    id,
    userId: req.userId,
    sessionId: req.sessionId,
    kind: "video",
    modelId: req.modelId,
    prompt: req.prompt,
    status: "running",
    createdAt,
    videoParams: req.params,
  };
  persistGeneration(initial);
  if (req.sessionId) {
    setTitleIfDefaultSync(req.sessionId, req.prompt);
    touchSync(req.sessionId);
  }
  return runAdapter(initial, { kind: "video", prompt: req.prompt, params: req.params }, req.modelId, onProgress);
}
